Auto fetch new app version when version changes
codyc1515/homebridge-panasonic-air-conditioner pull request #37
Opened 2020-09-09 00:52 UTC by lockpicker

Have a look and see if this makes sense to include.

Main change: 
The version header that the API expects, expects the version of the Panasonic Comfort cloud app so we can auto fetch the version of the app from the App Store api, if we see that the version has changed. This is also referenced in the API response which suggests that there's a new app version published. This will allow the plugin to continue operating without breaking and the hardcoded version in code can be updated in the background and consumed whenever the plugin is re-installed.
P.S: I've used the got library for async / await to avoid callback hell and also as request is now deprecated and starting to be used less. 

Small additional changes:
1. Added a gitignore to the repo with some standard ignores
2. Added a few scripts in package.json which make development easier - this will now allow npm run watch which watches the index.js file for changes during development and restarts homebridge automatically

2020-09-09 00:55 UTC, lockpicker commented
Also, the 30 second wait I've introduced post fetching the new version number is for avoiding repeated calls and log flooding if there's an issue with the api and given the version number changes are rather infrequent, the 30 seconds once off wait shouldn't make a big difference.

2020-10-10 20:53 UTC, lockpicker commented
@codyc1515 Bump for you to have a look

2020-12-01 07:27 UTC, codyc1515 commented
Hi there

I didn't particularly like the idea at first (as we may send the wrong command accidentally), but now it makes more sense to me. Can you please re-base the plug-in (not sure if that's the right term)? Also I'd prefer not to use two HTTP libraries. If we're going to change it, can we please make the whole plug-in use the same one?

Kind regards
Cody

2020-12-01 07:27 UTC, codyc1515 requested changes
Hi there

I didn't particularly like the idea at first (as we may send the wrong command accidentally), but now it makes more sense to me. Can you please re-base the plug-in (not sure if that's the right term)? Also I'd prefer not to use two HTTP libraries. If we're going to change it, can we please make the whole plug-in use the same one?

Kind regards
Cody

2021-01-01 21:33 UTC, codyc1515 commented
Case in point. This December there was a small breaking API change on the Panasonic side. This required a manual fix still.

2021-01-01 21:33 UTC, closed without merging